<?php
/**
 * QueryResultResponseBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  Onyx\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Onyx\Client\Model;

use \ArrayAccess;
/**
 * QueryResultResponseBody Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Onyx\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QueryResultResponseBody implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'max_results' => 'int',
        'results' => 'int',
        'result_list' => 'object[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'max_results' => 'maxResults',
        'results' => 'results',
        'result_list' => 'resultList'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'max_results' => 'setMaxResults',
        'results' => 'setResults',
        'result_list' => 'setResultList'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'max_results' => 'getMaxResults',
        'results' => 'getResults',
        'result_list' => 'getResultList'
    );
  
    
    /**
      * $max_results Number of results that were calculated during query execute
      * @var int
      */
    protected $max_results;
    
    /**
      * $results Number of results returned
      * @var int
      */
    protected $results;
    
    /**
      * $result_list 
      * @var object[]
      */
    protected $result_list;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->max_results = $data["max_results"];
            $this->results = $data["results"];
            $this->result_list = $data["result_list"];
        }
    }
    
    /**
     * Gets max_results
     * @return int
     */
    public function getMaxResults()
    {
        return $this->max_results;
    }
  
    /**
     * Sets max_results
     * @param int $max_results Number of results that were calculated during query execute
     * @return $this
     */
    public function setMaxResults($max_results)
    {
        
        $this->max_results = $max_results;
        return $this;
    }
    
    /**
     * Gets results
     * @return int
     */
    public function getResults()
    {
        return $this->results;
    }
  
    /**
     * Sets results
     * @param int $results Number of results returned
     * @return $this
     */
    public function setResults($results)
    {
        
        $this->results = $results;
        return $this;
    }
    
    /**
     * Gets result_list
     * @return object[]
     */
    public function getResultList()
    {
        return $this->result_list;
    }
  
    /**
     * Sets result_list
     * @param object[] $result_list 
     * @return $this
     */
    public function setResultList($result_list)
    {
        
        $this->result_list = $result_list;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
